# Generated by Django 6.1 on 2026-08-29 08:07

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('waterproofing', 'Waterproofing'), ('flooring', 'Flooring'), ('road-surfacing', 'Road Surfacing'), ('restofix', 'Restofix')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tds_file', models.FileField(blank=True, null=True, upload_to='products/tds/')),
                ('msds_file', models.FileField(blank=True, null=True, upload_to='products/msds/')),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
